version: '3.8'
services:
  app:
    build:
      context: .
    container_name: ojodo-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - ojodo-network

  db:
    build:
      context: ./prisma
    container_name: ojodo-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Tokyo
    ports:
      - '5432:5432'
    networks:
      - ojodo-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ojodo-network:
    driver: bridge
