version: '3.8'
services:
  app:
    build:
      context: .
      target: deps
    container_name: ojodo-app-dev
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    networks:
      - ojodo-network-dev
    depends_on:
      - db

  db:
    build:
      context: ./prisma
    container_name: ojodo-db-dev
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Tokyo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ojodo-network-dev

volumes:
  postgres_data:
    name: ojodo-db-dev-data

networks:
  ojodo-network-dev:
    driver: bridge
