import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const characters = [
    // モンド
    {
      name_jp: 'アンバー',
      name: 'Amber',
      rarity: 4,
      element: '炎',
      weapon_type: '弓',
      base_hp: 9461,
      base_atk: 223,
      base_def: 601,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 40,
      version: 1.0,
    },
    {
      name_jp: 'ジン',
      name: 'Jean',
      rarity: 5,
      element: '風',
      weapon_type: '片手剣',
      base_hp: 14695,
      base_atk: 239,
      base_def: 769,
      special_stat: '与える治療効果',
      special_value: '22.2',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: 'リサ',
      name: 'Lisa',
      rarity: 4,
      element: '雷',
      weapon_type: '法器',
      base_hp: 9570,
      base_atk: 232,
      base_def: 573,
      special_stat: '元素熟知',
      special_value: '96.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: 'ガイア',
      name: 'Kaeya',
      rarity: 4,
      element: '氷',
      weapon_type: '片手剣',
      base_hp: 11636,
      base_atk: 223,
      base_def: 792,
      special_stat: '元素チャージ効率',
      special_value: '26.7',
      energy_cost: 60,
      version: 1.0,
    },
    {
      name_jp: 'バーバラ',
      name: 'Barbara',
      rarity: 4,
      element: '水',
      weapon_type: '法器',
      base_hp: 9787,
      base_atk: 159,
      base_def: 669,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: 'ディルック',
      name: 'Diluc',
      rarity: 5,
      element: '炎',
      weapon_type: '両手剣',
      base_hp: 12981,
      base_atk: 335,
      base_def: 784,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 40,
      version: 1.0,
    },
    {
      name_jp: 'レザー',
      name: 'Razor',
      rarity: 4,
      element: '雷',
      weapon_type: '両手剣',
      base_hp: 11962,
      base_atk: 234,
      base_def: 751,
      special_stat: '物理ダメージ',
      special_value: '30.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: 'ベネット',
      name: 'Bennett',
      rarity: 4,
      element: '炎',
      weapon_type: '片手剣',
      base_hp: 12397,
      base_atk: 191,
      base_def: 771,
      special_stat: '元素チャージ効率',
      special_value: '26.7',
      energy_cost: 60,
      version: 1.0,
    },
    {
      name_jp: 'ノエル',
      name: 'Noelle',
      rarity: 4,
      element: '岩',
      weapon_type: '両手剣',
      base_hp: 12071,
      base_atk: 191,
      base_def: 799,
      special_stat: '防御力',
      special_value: '30.0',
      energy_cost: 60,
      version: 1.0,
    },
    {
      name_jp: 'フィッシュル',
      name: 'Fischl',
      rarity: 4,
      element: '雷',
      weapon_type: '弓',
      base_hp: 9189,
      base_atk: 244,
      base_def: 594,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 60,
      version: 1.0,
    },
    {
      name_jp: 'スクロース',
      name: 'Sucrose',
      rarity: 4,
      element: '風',
      weapon_type: '法器',
      base_hp: 9244,
      base_atk: 170,
      base_def: 703,
      special_stat: '風元素ダメージ',
      special_value: '24.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: 'アルベド',
      name: 'Albedo',
      rarity: 5,
      element: '岩',
      weapon_type: '片手剣',
      base_hp: 13226,
      base_atk: 251,
      base_def: 876,
      special_stat: '岩元素ダメージ',
      special_value: '28.8',
      energy_cost: 40,
      version: 1.2,
    },
    {
      name_jp: 'ロサリア',
      name: 'Rosaria',
      rarity: 4,
      element: '氷',
      weapon_type: '長柄武器',
      base_hp: 12289,
      base_atk: 240,
      base_def: 710,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 60,
      version: 1.4,
    },
    {
      name_jp: 'エウルア',
      name: 'Eula',
      rarity: 5,
      element: '氷',
      weapon_type: '両手剣',
      base_hp: 13226,
      base_atk: 342,
      base_def: 751,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 80,
      version: 1.5,
    },
    {
      name_jp: 'ミカ',
      name: 'Mika',
      rarity: 4,
      element: '氷',
      weapon_type: '長柄武器',
      base_hp: 12506,
      base_atk: 223,
      base_def: 713,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 60,
      version: 3.5,
    },

    // 璃月
    {
      name_jp: '香菱',
      name: 'Xiangling',
      rarity: 4,
      element: '炎',
      weapon_type: '長柄武器',
      base_hp: 10875,
      base_atk: 225,
      base_def: 669,
      special_stat: '元素熟知',
      special_value: '96.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: '北斗',
      name: 'Beidou',
      rarity: 4,
      element: '雷',
      weapon_type: '両手剣',
      base_hp: 13050,
      base_atk: 225,
      base_def: 648,
      special_stat: '雷元素ダメージ',
      special_value: '24.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: '行秋',
      name: 'Xingqiu',
      rarity: 4,
      element: '水',
      weapon_type: '片手剣',
      base_hp: 10222,
      base_atk: 202,
      base_def: 758,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: '凝光',
      name: 'Ningguang',
      rarity: 4,
      element: '岩',
      weapon_type: '法器',
      base_hp: 9787,
      base_atk: 212,
      base_def: 573,
      special_stat: '岩元素ダメージ',
      special_value: '24.0',
      energy_cost: 40,
      version: 1.0,
    },
    {
      name_jp: '七七',
      name: 'Qiqi',
      rarity: 5,
      element: '氷',
      weapon_type: '片手剣',
      base_hp: 12368,
      base_atk: 287,
      base_def: 922,
      special_stat: '与える治療効果',
      special_value: '22.2',
      energy_cost: 80,
      version: 1.0,
    },
    {
      name_jp: '刻晴',
      name: 'Keqing',
      rarity: 5,
      element: '雷',
      weapon_type: '片手剣',
      base_hp: 13103,
      base_atk: 323,
      base_def: 799,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 40,
      version: 1.0,
    },
    {
      name_jp: '重雲',
      name: 'Chongyun',
      rarity: 4,
      element: '氷',
      weapon_type: '両手剣',
      base_hp: 10984,
      base_atk: 223,
      base_def: 648,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 40,
      version: 1.0,
    },
    {
      name_jp: '甘雨',
      name: 'Ganyu',
      rarity: 5,
      element: '氷',
      weapon_type: '弓',
      base_hp: 9797,
      base_atk: 335,
      base_def: 630,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 60,
      version: 1.2,
    },
    {
      name_jp: '魈',
      name: 'Xiao',
      rarity: 5,
      element: '風',
      weapon_type: '長柄武器',
      base_hp: 12736,
      base_atk: 349,
      base_def: 799,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 70,
      version: 1.3,
    },
    {
      name_jp: '胡桃',
      name: 'Hu Tao',
      rarity: 5,
      element: '炎',
      weapon_type: '長柄武器',
      base_hp: 15552,
      base_atk: 106,
      base_def: 876,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 60,
      version: 1.3,
    },
    {
      name_jp: '辛炎',
      name: 'Xinyan',
      rarity: 4,
      element: '炎',
      weapon_type: '両手剣',
      base_hp: 11201,
      base_atk: 249,
      base_def: 799,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 60,
      version: 1.1,
    },
    {
      name_jp: '雲菫',
      name: 'Yun Jin',
      rarity: 4,
      element: '岩',
      weapon_type: '長柄武器',
      base_hp: 10657,
      base_atk: 191,
      base_def: 734,
      special_stat: '元素チャージ効率',
      special_value: '26.7',
      energy_cost: 60,
      version: 2.4,
    },
    {
      name_jp: '夜蘭',
      name: 'Yelan',
      rarity: 5,
      element: '水',
      weapon_type: '弓',
      base_hp: 14450,
      base_atk: 244,
      base_def: 548,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 70,
      version: 2.7,
    },
    {
      name_jp: '申鶴',
      name: 'Shenhe',
      rarity: 5,
      element: '氷',
      weapon_type: '長柄武器',
      base_hp: 12993,
      base_atk: 304,
      base_def: 830,
      special_stat: '攻撃力',
      special_value: '28.8',
      energy_cost: 80,
      version: 2.4,
    },
    {
      name_jp: '煙緋',
      name: 'Yanfei',
      rarity: 4,
      element: '炎',
      weapon_type: '法器',
      base_hp: 9352,
      base_atk: 240,
      base_def: 587,
      special_stat: '炎元素ダメージ',
      special_value: '24.0',
      energy_cost: 80,
      version: 1.5,
    },
    {
      name_jp: 'ヨォーヨ',
      name: 'Yaoyao',
      rarity: 4,
      element: '草',
      weapon_type: '長柄武器',
      base_hp: 12289,
      base_atk: 212,
      base_def: 751,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 80,
      version: 3.4,
    },
    {
      name_jp: '白朮',
      name: 'Baizhu',
      rarity: 5,
      element: '草',
      weapon_type: '法器',
      base_hp: 13348,
      base_atk: 193,
      base_def: 500,
      special_stat: '与える治療効果',
      special_value: '28.8',
      energy_cost: 70,
      version: 3.6,
    },

    // 稲妻
    {
      name_jp: '神里綾華',
      name: 'Kamisato Ayaka',
      rarity: 5,
      element: '氷',
      weapon_type: '片手剣',
      base_hp: 12858,
      base_atk: 342,
      base_def: 784,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 80,
      version: 2.0,
    },
    {
      name_jp: '宵宮',
      name: 'Yoimiya',
      rarity: 5,
      element: '炎',
      weapon_type: '弓',
      base_hp: 10164,
      base_atk: 323,
      base_def: 615,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 60,
      version: 2.0,
    },
    {
      name_jp: '雷電将軍',
      name: 'Raiden Shogun',
      rarity: 5,
      element: '雷',
      weapon_type: '長柄武器',
      base_hp: 12907,
      base_atk: 337,
      base_def: 789,
      special_stat: '元素チャージ効率',
      special_value: '32.0',
      energy_cost: 90,
      version: 2.1,
    },
    {
      name_jp: '九条裟羅',
      name: 'Kujou Sara',
      rarity: 4,
      element: '雷',
      weapon_type: '弓',
      base_hp: 9570,
      base_atk: 195,
      base_def: 628,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 80,
      version: 2.1,
    },
    {
      name_jp: '早柚',
      name: 'Sayu',
      rarity: 4,
      element: '風',
      weapon_type: '両手剣',
      base_hp: 11854,
      base_atk: 244,
      base_def: 745,
      special_stat: '元素熟知',
      special_value: '96.0',
      energy_cost: 80,
      version: 2.0,
    },
    {
      name_jp: '珊瑚宮心海',
      name: 'Sangonomiya Kokomi',
      rarity: 5,
      element: '水',
      weapon_type: '法器',
      base_hp: 13471,
      base_atk: 234,
      base_def: 657,
      special_stat: '与える治療効果',
      special_value: '28.8',
      energy_cost: 70,
      version: 2.1,
    },
    {
      name_jp: 'トーマ',
      name: 'Thoma',
      rarity: 4,
      element: '炎',
      weapon_type: '長柄武器',
      base_hp: 10331,
      base_atk: 202,
      base_def: 751,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 80,
      version: 2.2,
    },
    {
      name_jp: '荒瀧一斗',
      name: 'Arataki Itto',
      rarity: 5,
      element: '岩',
      weapon_type: '両手剣',
      base_hp: 12858,
      base_atk: 227,
      base_def: 959,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 70,
      version: 2.3,
    },
    {
      name_jp: 'ゴロー',
      name: 'Gorou',
      rarity: 4,
      element: '岩',
      weapon_type: '弓',
      base_hp: 9570,
      base_atk: 183,
      base_def: 648,
      special_stat: '岩元素ダメージ',
      special_value: '24.0',
      energy_cost: 80,
      version: 2.3,
    },
    {
      name_jp: '八重神子',
      name: 'Yae Miko',
      rarity: 5,
      element: '雷',
      weapon_type: '法器',
      base_hp: 10372,
      base_atk: 340,
      base_def: 569,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 90,
      version: 2.5,
    },
    {
      name_jp: '神里綾人',
      name: 'Kamisato Ayato',
      rarity: 5,
      element: '水',
      weapon_type: '片手剣',
      base_hp: 13715,
      base_atk: 299,
      base_def: 769,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 80,
      version: 2.6,
    },
    {
      name_jp: '久岐忍',
      name: 'Kuki Shinobu',
      rarity: 4,
      element: '雷',
      weapon_type: '片手剣',
      base_hp: 12289,
      base_atk: 212,
      base_def: 751,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 60,
      version: 2.7,
    },

    // スメール
    {
      name_jp: 'ティナリ',
      name: 'Tighnari',
      rarity: 5,
      element: '草',
      weapon_type: '弓',
      base_hp: 10850,
      base_atk: 268,
      base_def: 630,
      special_stat: '草元素ダメージ',
      special_value: '28.8',
      energy_cost: 40,
      version: 3.0,
    },
    {
      name_jp: 'コレイ',
      name: 'Collei',
      rarity: 4,
      element: '草',
      weapon_type: '弓',
      base_hp: 9787,
      base_atk: 200,
      base_def: 601,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 60,
      version: 3.0,
    },
    {
      name_jp: 'ドリー',
      name: 'Dori',
      rarity: 4,
      element: '雷',
      weapon_type: '両手剣',
      base_hp: 12397,
      base_atk: 223,
      base_def: 723,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 80,
      version: 3.0,
    },
    {
      name_jp: 'キャンディス',
      name: 'Candace',
      rarity: 4,
      element: '水',
      weapon_type: '長柄武器',
      base_hp: 10875,
      base_atk: 212,
      base_def: 683,
      special_stat: '体力',
      special_value: '24.0',
      energy_cost: 60,
      version: 3.1,
    },
    {
      name_jp: 'セノ',
      name: 'Cyno',
      rarity: 5,
      element: '雷',
      weapon_type: '長柄武器',
      base_hp: 12491,
      base_atk: 318,
      base_def: 859,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 80,
      version: 3.1,
    },
    {
      name_jp: 'ニィロウ',
      name: 'Nilou',
      rarity: 5,
      element: '水',
      weapon_type: '片手剣',
      base_hp: 15185,
      base_atk: 230,
      base_def: 729,
      special_stat: '体力',
      special_value: '28.8',
      energy_cost: 70,
      version: 3.1,
    },
    {
      name_jp: 'ナヒーダ',
      name: 'Nahida',
      rarity: 5,
      element: '草',
      weapon_type: '法器',
      base_hp: 10360,
      base_atk: 299,
      base_def: 630,
      special_stat: '元素熟知',
      special_value: '115.2',
      energy_cost: 50,
      version: 3.2,
    },
    {
      name_jp: 'レイラ',
      name: 'Layla',
      rarity: 4,
      element: '氷',
      weapon_type: '片手剣',
      base_hp: 11092,
      base_atk: 217,
      base_def: 655,
      special_stat: '体力',
      special_value: '24.0',
      energy_cost: 40,
      version: 3.2,
    },
    {
      name_jp: '放浪者',
      name: 'Wanderer',
      rarity: 5,
      element: '風',
      weapon_type: '法器',
      base_hp: 10164,
      base_atk: 328,
      base_def: 607,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 60,
      version: 3.3,
    },
    {
      name_jp: 'ファルザン',
      name: 'Faruzan',
      rarity: 4,
      element: '風',
      weapon_type: '弓',
      base_hp: 9570,
      base_atk: 196,
      base_def: 628,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 80,
      version: 3.3,
    },
    {
      name_jp: 'アルハイゼン',
      name: 'Alhaitham',
      rarity: 5,
      element: '草',
      weapon_type: '片手剣',
      base_hp: 13348,
      base_atk: 313,
      base_def: 782,
      special_stat: '草元素ダメージ',
      special_value: '28.8',
      energy_cost: 70,
      version: 3.4,
    },
    {
      name_jp: 'ディシア',
      name: 'Dehya',
      rarity: 5,
      element: '炎',
      weapon_type: '両手剣',
      base_hp: 15675,
      base_atk: 265,
      base_def: 628,
      special_stat: '体力',
      special_value: '28.8',
      energy_cost: 70,
      version: 3.5,
    },
    {
      name_jp: 'カーヴェ',
      name: 'Kaveh',
      rarity: 4,
      element: '草',
      weapon_type: '両手剣',
      base_hp: 11962,
      base_atk: 234,
      base_def: 751,
      special_stat: '元素熟知',
      special_value: '96.0',
      energy_cost: 60,
      version: 3.6,
    },

    // フォンテーヌ
    {
      name_jp: 'リネット',
      name: 'Lynette',
      rarity: 4,
      element: '風',
      weapon_type: '片手剣',
      base_hp: 11092,
      base_atk: 217,
      base_def: 655,
      special_stat: '攻撃力',
      special_value: '24.0',
      energy_cost: 60,
      version: 4.0,
    },
    {
      name_jp: 'リネ',
      name: 'Lyney',
      rarity: 5,
      element: '炎',
      weapon_type: '弓',
      base_hp: 10164,
      base_atk: 328,
      base_def: 607,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 60,
      version: 4.0,
    },
    {
      name_jp: 'フレミネ',
      name: 'Freminet',
      rarity: 4,
      element: '氷',
      weapon_type: '両手剣',
      base_hp: 12071,
      base_atk: 217,
      base_def: 708,
      special_stat: '物理ダメージ',
      special_value: '30.0',
      energy_cost: 40,
      version: 4.0,
    },
    {
      name_jp: 'ヌヴィレット',
      name: 'Neuvillette',
      rarity: 5,
      element: '水',
      weapon_type: '法器',
      base_hp: 14695,
      base_atk: 299,
      base_def: 729,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 70,
      version: 4.1,
    },
    {
      name_jp: 'リオセスリ',
      name: 'Wriothesley',
      rarity: 5,
      element: '氷',
      weapon_type: '法器',
      base_hp: 15307,
      base_atk: 280,
      base_def: 729,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 60,
      version: 4.1,
    },
    {
      name_jp: 'フリーナ',
      name: 'Furina',
      rarity: 5,
      element: '水',
      weapon_type: '片手剣',
      base_hp: 15307,
      base_atk: 280,
      base_def: 729,
      special_stat: '会心率',
      special_value: '19.2',
      energy_cost: 60,
      version: 4.2,
    },
    {
      name_jp: 'シャルロット',
      name: 'Charlotte',
      rarity: 4,
      element: '氷',
      weapon_type: '法器',
      base_hp: 12071,
      base_atk: 217,
      base_def: 708,
      special_stat: '与える治療効果',
      special_value: '24.0',
      energy_cost: 80,
      version: 4.2,
    },
    {
      name_jp: 'ナヴィア',
      name: 'Navia',
      rarity: 5,
      element: '岩',
      weapon_type: '両手剣',
      base_hp: 15307,
      base_atk: 280,
      base_def: 729,
      special_stat: '会心ダメージ',
      special_value: '38.4',
      energy_cost: 60,
      version: 4.3,
    },
    {
      name_jp: 'シュヴルーズ',
      name: 'Chevreuse',
      rarity: 4,
      element: '炎',
      weapon_type: '長柄武器',
      base_hp: 12071,
      base_atk: 217,
      base_def: 708,
      special_stat: '体力',
      special_value: '24.0',
      energy_cost: 80,
      version: 4.3,
    },
  ];

  for (const character of characters) {
    await prisma.character.create({
      data: character,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
